[package]
name = "revim"
version = "0.0.1"
authors = ["cowboy8625 <cowboy8625@protonmail.com>"]
edition = "2018"

[dependencies]
ropey = "1.2.0"
clap = "2.33.1"
crossterm = "0.19.0"

[profile.release]
debug = true
