[package]
name = "ReVim"
version = "0.0.1"
authors = ["cowboy8625 <cowboy8625@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.14.2"
terminal_size = "0.1.8"
ropey = "1.1.0"

